### PR TITLE
Update StudioUpdateFileTask.java

### PR DESCRIPTION
**Pull request by AVATOR**
Updated messages in the console.

### CODE REVIEW

**Comment by nek4life** [comment]
Hey @AVATOR thanks for the pull request! I have a few bits of feedback on this request. The first is that I'm using the develop branch as the next iteration of the plugin and merging into master when there is a new feature release. So maybe feature branches should be created off of that branch, but you're my first contributor 😄 so definitely open to discussion. The next version is also being built for the 2019 release of Intellij which is setup already in Gradle and has a few fixes on it as well.

The second bit is that I'm not 100% sure I want to replace the remote links in the sync log as I personally use them to click and check if the remote files were indeed updated on the server. It's a nice feature I use fairly often. I'm wondering if it would make sense to create a second tab, perhaps the local sync log could be the first tab and a remote sync log be the second tab? Then we could have both logs?

You can see an example of how to create a console service here. It must also be registered in the plugin.xml file as well.

https://github.com/nek4life/sfcc-studio/blob/develop/src/main/java/com/binarysushi/studio/toolWindow/StudioConsoleService.java

https://github.com/nek4life/sfcc-studio/blob/develop/src/main/resources/META-INF/plugin.xml

And adding the tool window here.

https://github.com/nek4life/sfcc-studio/blob/develop/src/main/java/com/binarysushi/studio/toolWindow/StudioToolWindowFactory.java

Hope this isn't too much feedback to discourage you. I really appreciate all your help!

**Comment by AVATOR** [comment]
I will create new PRs to develop branch.

I did not delete the link from the console. I have added file name to the console message. It is useful for me. 
I did not use new console service. I only fix the messages and type of messages.

**Comment by nek4life** [comment]
@AVATOR I see thank you. I read through the code, but didn't have a chance to run it yet. Looking forward to the updates! Thanks!

**Comment by nek4life** [comment]
I implemented most of this in the last release. Please create a new pull request for the missing features off of the develop branch if you want to have them added. Thanks!

**Pull request closed without merging**
